import { MenuItem } from "../types/types";
import { optimizeCloudinaryUrl } from "../lib/optimizeCloudinaryUrl";

// --- Roti / Indian Breads ---
export const indianBreadsData: MenuItem[] = [
  {
    id: 90,
    name: "CHAPATI ROTI",
    description: "Pan baked light whole wheat bread",
    price: 1.0,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599177/CHAPATI_ROTI_ykwnf9.webp"),
    vegetarian: true,
  },
  {
    id: 91,
    name: "TANDOORI ROTI",
    description: "Barbequed light whole wheat bread",
    price: 1.25,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599193/TANDOORI_ROTI_youkkw.webp"),
    vegetarian: true,
  },
  {
    id: 92,
    name: "LACHHA PARATHA",
    description: "White flour crispy layered bread baked in Tandoor",
    price: 1.5,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599183/LACHHA_PARATHA_dofbul.webp"),
    vegetarian: true,
  },
  {
    id: 93,
    name: "MISSI ROTI",
    description: "Baked bread of mix flours and chopped onions",
    price: 1.5,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599186/MISSI_ROTI_xeyp5i.webp"),
    vegetarian: true,
  },
  {
    id: 94,
    name: "PLAIN NAAN",
    description: "Soft bread baked in tandoor made with refined flour",
    price: 1.0,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599493/PLAIN_NAAN_b14xnq.webp"),
    vegetarian: true,
  },
  {
    id: 95,
    name: "BUTTER NAAN",
    description: "Barbequed leavened bread topped with clarified butter",
    price: 1.75,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599178/BUTTER_NAAN_xnsnlg.webp"),
    vegetarian: true,
  },
  {
    id: 96,
    name: "GARLIC NAAN",
    description:
      "Leavened bread with a touch of garlic topped with fresh cilantro",
    price: 1.75,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599179/GARLIC_NAAN_bjec7r.webp"),
    vegetarian: true,
  },
  {
    id: 97,
    name: "KASHMIRI NAAN",
    description:
      "Plain flavored bread stuffed with minted dry fruits and nuts",
    price: 3.0,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599181/KASHMIRI_NAAN_bvmqjt.webp"),
    vegetarian: true,
  },
  {
    id: 98,
    name: "PANEER NAAN / CHEESE NAAN",
    description: "Naan stuffed with homemade cottage cheese",
    price: 3.0,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599187/PANEER_NAAN_CHEESE_NAAN_p7ij0j.webp"),
    vegetarian: true,
  },
  {
    id: 99,
    name: "AKBARI NAAN (MUTTON / CHICKEN)",
    description:
      "Plain flour bread stuffed with spicy mixed chicken or mutton",
    price: 3.0,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599175/AKBARI_NAAN_MUTTON_CHICKEN_dtsvol.webp"),
    vegetarian: false,
    spicy: true,
  },
  {
    id: 100,
    name: "PLAIN PARATHA",
    description: "Plain pan fried whole wheat bread",
    price: 1.5,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599192/PLAIN_PARATHA_tgcrng.webp"),
    vegetarian: true,
  },
  {
    id: 101,
    name: "ALOO PARATHA / GOBI PARATHA / MOOLI PARATHA",
    description:
      "Stuffed whole wheat bread pan fried with choice of inner layer",
    price: 2.25,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599176/ALOO_PARATHA_GOBI_PARATHA_MOOLI_PARATHA_pzztlk.webp"),
    vegetarian: true,
  },
  {
    id: 102,
    name: "KERALA PAROTTA",
    description:
      "Layered, flattened, and cooked on a hot griddle with all-purpose flour and ghee",
    price: 2.0,
    category: "Roti / Indian Breads",
    image: optimizeCloudinaryUrl("https://res.cloudinary.com/dweqejpfk/image/upload/v1771599182/KERALA_PAROTTA_y6batw.webp"),
    vegetarian: true,
  },
];